apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: productpage
  namespace: productpage
spec:
  importFrom:
  - workspaces:
    - name: gateways
    resources:
    - kind: ALL
  - workspaces:
    - name: details
    resources:
    - kind: ALL
  - workspaces:
    - name: reviews
    resources:
    - kind: ALL    
  exportTo:
  - workspaces:
    - name: gateways
    resources:
    - kind: ALL

  options:
    federation:
      enabled: true
      hostSuffix: global
      serviceSelector:
      - workspace: details
        labels:
          app: details
      - workspace: reviews
        labels:
          app: reviews              
