apiVersion: v1
kind: Secret
metadata:
  name: oauth-productpage-azure
  namespace: productpage
type: extauth.solo.io/oauth
data:
  client-secret: d3ZBOFF+Z0c4WENFak5feEp0NllQVnVZTGx0MU1iSXVKVGdBT2JLVQ==