apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-enterprise-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: gloo-mesh-enterprise
    helm:
      values: |
        licenseKey: eyJhZGRPbnMiOiJncmFwaHFsIiwiZXhwIjoxNjkyMDI1MjAzLCJpYXQiOjE2NzQ3NDUyMDMsImsiOiJyL0YrMFEiLCJsdCI6InRyaWFsIiwicHJvZHVjdCI6Imdsb28tbWVzaC1nYXRld2F5In0.fKgQIyBdy1ZTCQKnh3Jqb4K-bsUmzS_nKusVb-AEhS8
        mgmtClusterName: mgmt
        glooMeshMgmtServer:
          relay:
            disableCa: true
            disableCaCertGeneration: true
            tlsSecret:
              name: relay-server-tls-secret
          ports:
            healthcheck: 8091
        glooMeshUi:
          enabled: true
          deploymentOverrides:
            spec:
              template:
                metadata:
                  annotations:
                    sidecar.istio.io/inject: "true"
                  labels:
                    istio.io/rev: "1-13"
    repoURL: https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise
    targetRevision: 2.3.0-beta1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  # ignore the self-signed certs that are being generated automatically    
  ignoreDifferences:
  - group: v1
    kind: Secret
