apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: productpage-azure
  namespace: productpage
spec:
  applyToRoutes:
  - route:
      labels:
        oauth: "azure"
  config:
    server:
      name: ext-auth-server
      namespace: productpage
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://bookinfo.asayah.solo.io
            callbackPath: /callback
            clientId: fb2b1fd0-6ccd-4491-a21e-f618bed0c8c1
            clientSecretRef:
              name: oauth-productpage-azure
              namespace: productpage
            issuerUrl: "https://login.microsoftonline.com/da21cd1c-6201-4410-ba19-40f843f3e2c4"
            session:
              failOnFetchFailure: true
              redis:
                cookieName: productpage-azure-session
                options:
                  host: redis:6379
            scopes:
            - email
            headers:
              idTokenHeader: jwt