apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerConfig
metadata:
  name: rl
  namespace: productpage
spec:
  destinationServers:
  - port:
      name: grpc
    ref:
      cluster: cluster1
      name: rate-limiter
      namespace: gloo-mesh-addons
  raw:
    descriptors:
      - key: generic_key
        value: "per-minute"
        descriptors:
          - key: remote_address
            rateLimit:
              requestsPerUnit: 15
              unit: MINUTE