apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  name: rl
  namespace: productpage
spec:
  applyToRoutes:
  - route:
      labels:
        ratelimited: "true"
  config:
    ratelimitClientConfig:
      name: rl
      namespace: productpage
    ratelimitServerConfig:
      name: rl
      namespace: productpage
    serverSettings:
      name: rl
      namespace: productpage