apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: reviews
  namespace: productpage
spec:
  hosts:
  - reviews.global
  services:
  - namespace: all
    labels:
      app: reviews
  ports:
    - number: 9080
      protocol: HTTP