apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: gateways
  namespace: istio-gateways
spec:
  importFrom:
  - workspaces:
    - name: productpage
    resources:
    - kind: ALL
  - workspaces:
    - name: details
    resources:
    - kind: ALL
  - workspaces:
    - name: reviews
    resources:
    - kind: ALL  
  exportTo:
  - workspaces:
    - name: productpage
    resources:
    - kind: ALL
  - workspaces:
    - name: details
    resources:
    - kind: ALL
  - workspaces:
    - name: reviews
    resources:
    - kind: ALL  