apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: productpage
  namespace: gloo-mesh
  labels:
    allow_ingress: "true"
spec:
  workloadClusters:
  - name: cluster1
    namespaces:
    - name: productpage