apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: productpage
  namespace: productpage
spec:
  importFrom:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
  exportTo:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
      labels:
        app: productpage
    - kind: ALL
      labels:
        expose: "true"