apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: details
  namespace: details
spec:
  importFrom:
  - workspaces:
    - name: details
    resources:
    - kind: ALL
  exportTo:
  - workspaces:
    - name: details
    resources:
    - kind: ALL
  options:
    federation:
      enabled: true
      hostSuffix: global
      serviceSelector:
      - workspace: details
        labels:
          app: details    